
services:

  database:
    image: postgres:16.2
    restart: always
    ports:
      - 1234:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pomodoro
  
  cashe:

    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    
    container_name: cashe